---
title: "Clustering Weather data of Texas State 2006-2010"
author: "Crupanshu Ashishbhai Udani, Karan Jeeten Thakkar"
date: 08/10/20
output: html_document
---

```{r setup,include = FALSE}
knitr::opts_chunk$set(echo=TRUE,warning = FALSE,message=FALSE)
```
# Importing libraries
```{r}
library(dplyr)
library(readr)
#library(caret)
library(lubridate) # Used for handling date
library(stringr) # Used for String manipulation for feature extractions
```

```{bash, engine.opts="-l"}
#awk { gsub(","," ");print>>"hourly_2010.g"} hourly_2010_mod.g
```

# 1 Importing Data and merging into single data frame
```{r Import Data and merging}
columns_names <- c("STN","WBAN","YEARMODA_HR","TEMP","DEWP","DEWP.Count",  "SLP","SLP.Count"  , "STP","STP.Count", "VISIB","VISIB.Count","WDSP","WDSP.Count", "MXSPD",  "GUST", "PRCP"  ,"SNDP" , "FRSHTT")
fileNames_all <- c("./data/datasets_all/hourly_2006.g","./data/datasets_all/hourly_2007.g","./data/datasets_all/hourly_2008.g","./data/datasets_all/hourly_2009.g","./data/datasets_all/hourly_2010_mod.g")
fileNames_789 <- c("../data/datasets_all/hourly_2007.g","../data/datasets_all/hourly_2008.g","../data/datasets_all/hourly_2009.g")
i<-1
for (file in fileNames_789){
  fileData <- read_delim(file,"  ",skip = 1,col_names = columns_names,na =c("", "NA","999.9","9999.9"),col_types ="cicddidididididdcdc-",trim_ws = TRUE) %>% as.data.frame()
  print(dim(fileData))
  if(i==1)
    stations_all <- fileData
  else
    stations_all <- bind_rows(stations_all,fileData)
  i <- i + 1
}
#stations_all <- bind_cols(fileDataList[1],fileDataList[2],fileDataList[3],fileDataList[4],fileDataList[5])
print(dim(stations_all))
head(stations_all)
```

# 2 Filtering out data based on data month and year
```{r}
stations_all %>% filter(month(ymd_h(YEARMODA_HR))==11 & year(ymd_h(YEARMODA_HR))>2006 & year(ymd_h(YEARMODA_HR))<2010 ) -> stations_789_nov
summary(stations_789_nov)
#optional (for mem optimization)
rm(stations_all)
gc()
```


# 2 Preprocessing
```{r Preprocessing the data}
# Drop SNDP as maximum values are NA
#stations_all <- subset(stations_all, select = -c(SNDP))
```

```{r TEMP}
#count(filter("TEMP" > 900))
barplot(stations_789_nov$TEMP)
boxplot(stations_789_nov$TEMP,horizontal = TRUE)
quantile(stations_789_nov$TEMP)
dens_TEMP<-density(stations_789_nov$TEMP)
plot(dens_TEMP)
# Plotting TEMP less than equal 150 ℉
stations_789_nov%>%select(TEMP)%>%filter(TEMP<=150)%>%table()%>%plot()
# Replace absurdly high values (>150) of TEMP with NA
stations_789_nov$TEMP[stations_789_nov$TEMP > 150] <- NA
# Replace NA values in TEMP with median, grouping rows by station name
impute.median <- function(x) replace(x, is.na(x), median(x, na.rm = TRUE))
stations_789_nov %>% group_by(STN) %>% mutate(TEMP = impute.median(TEMP))
# Plotting TEMP after replacing TEMP > 150 with median
stations_789_nov$TEMP%>%table()%>%plot()
```

```{r PRCP}
stations_789_nov$PRCP<-ifelse(stations_789_nov$PRCP=="99.99",NA,stations_789_nov$PRCP)
PRCP_split<-str_match(stations_789_nov$PRCP,"([0-9.]*)([A-I]*)")
stations_789_nov$PRCP.Value<-as.double(PRCP_split[,2])
stations_789_nov$PRCP.Flag<-PRCP_split[,3]
density(stations_789_nov$PRCP.Value,na.rm = TRUE) %>% plot()
```